name: document_embedding_playground
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - -e .  # conda >= 4.4 only
    - python-dotenv
    - gdown
    #- sentence-transformers
    - git+https://github.com/TutteInstitute/vectorizers
  - bokeh
  - click
  - colorcet    # umap-learn[plot]
  - coverage
  - coveralls
  - datashader  # umap-learn[plot]
  - fsspec
  - git>=2.5  # for git worktree template updating
  - holoviews   # umap-learn[plot]
  - joblib
  - jupyter
  - matplotlib
  - nb_conda_kernels#<2.2.0  # nb_conda_kernels issue #158
  - nltk
  - pandas
  - pathlib
  - pytest
  - requests
  - scikit-image   # umap-learn[plot]
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - sphinx
  - tensorflow>=2
  - tensorflow-hub
  - wheel
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::tokenizers
  - conda-forge::transformers
  - conda-forge::umap-learn
